### PR TITLE
feat: Better sampling of terms for exercise "Between". Closes Issue#4

### PR DESCRIPTION
**Pull request by nico-miarka**

### CODE REVIEW

**Comment by holgerdell** [comment]
Thanks!

- Please rebase your nico-miarka:main branch onto goethe-tcs:main. The pull request should be a single commit relative to goethe-tcs:main
- "chore" means that only non-source files were modified (such as package.json or configuration files), so this commit would rather be a "feat"

I'll look at the contents of the commit once the above changes have been made

**Comment by nico-miarka** [comment]
Hi, I am not quite sure how to rebase my branch and I don't wanna mess things up. I think you can choose between merge and rebase before opening a pull request, right? Is it easier to close this request and open a new one, or is there a way of doing this while the PR is open?

**Comment by AbcAeffchen** [comment]
I'm not sure if the merge-commits disappear if we rebase before merging. You could probably delete the merge commits and make a force push to your branch. Then we can make a rebase. But I'm also not sure if the pull request survives the force push. Mabe a new branch + pull request is needed.

**Comment by holgerdell** [comment]
Thanks, that looks good!

**Pull request closed without merging**
